# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:alpine3.16
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
